language: java
install: 
  - "./gradlew test"
script: 
  - "./gradlew build"
deploy:
  provider: releases
  api_key:
    secure: LBqymd1oIXL74ueBvVKI5hPjSL99GxWJCj9YzP4ldZaujsLO08piLjpHwh+XOau6iusfFgnrsgQlO0rZxIqOImA9qmjsPTroehMRxGY9C4O8K8OXwB1aaSrgyQLHDksM2zN1Xhv2ovhn+/OI6XIslO99mUYjCujvPQbRShoyq2aWoZxb4ZKQI5maKYqcssze6RuKb5gVNdA8MOMoW3L9lY5XlonLD/0MTkknF157W8ZRJH99Tz3AuU/GX+J8B1bOHWAHpFHlllYQGWKH55UIB1W3tFRN3E7KrOn55Zkcj5t0+lexwES0SI9uObl5xa5NqHHxqtj0y60ff7Ofr1FVH7B8mvadApgM9FuOrMFKWhxTmGWxH5NwWN04t/8GQ/HusMbCjHgIpvRFs0rNdMRwSg3BKldLil/my1tOMTV9E+Sro/wRO86k58FOsH/cyre6d/8GHxMbByKAfWyHz5bwQkqYyUJptadb5rDqinfBpDLmjY9i5Ii1y/vlLwWt4E4FhI2q3U0eP7aTZ66ESqkFGPRKzIJMZO8UDBvMyWoSZaCAJt539jJfPTSHQmgYxHfx2bdj8FoZMQuvJmsoQw/QdoiIokUAnWWVI6OgMHEXEC+V0UF8qB8vavmPo1uliTyLCmoptVHZFnGQ6+3GMju92MpQrFu0kkzT+8SLOp8i1hQ=
  file: "./build/libs/hello.jar"
  skip_cleanup: true
  on:
    tags: true
